/**
 * Osvaldo Bosquez Garcia  16410108
 * Fecha: 24/04/2018
 * Tiempo de desarrollo: 5 hrs aprox.
 * Contratiempos: En especifico tuve dos, el primero fue que antes de descargar esta api 
 * estaba utilizando otra distinta que no me permitia obtener el estado del tiempo (nublado, claro,etc)
 * despues descargue la que se utiliza en este proyecto pero no encontraba mucha documentacion en internet asi
 * que tuve que probar la mayoria de los metodos antes de dar con los que necesitaba
 * Conclusion: 
 * Con este proyecto pude darme cuenta de la gran variedad de apis que existen para crear este tipo 
 * de aplicacion si es que podriamos llamarlo asi, y tambien de la importancia de generar
 * la documentaion necesaria en cada codigo, debido a que esto facilitara mucho la reutilizacion
 * de nuestro codigo.
 * Referencias:
 * http://woeid.rosselliot.co.nz/lookup
 * https://github.com/fedy2/yahoo-weather-java-api
 */
package com.mycompany.climayahoo;

import com.github.fedy2.weather.YahooWeatherService;
import com.github.fedy2.weather.data.unit.DegreeUnit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.xml.bind.JAXBException;

/**
 *
 * @author sr_os
 */
public class frmClima extends javax.swing.JFrame {

    YahooWeatherService s = new YahooWeatherService();

    /**
     * Creates new form frmClima
     */
    public frmClima() throws JAXBException, UnsupportedLookAndFeelException {
        initComponents();
                UIManager.setLookAndFeel(new com.jtattoo.plaf.noire.NoireLookAndFeel());
                SwingUtilities.updateComponentTreeUI(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCiudades = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblClima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parral", "Chihuahua", "Ciudad Juarez", "Cuauhtemoc", "Delicias" }));
        cboCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCiudadesActionPerformed(evt);
            }
        });

        jLabel1.setText("Ciudad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblClima, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(lblClima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCiudadesActionPerformed
        try {

            switch (cboCiudades.getSelectedItem().toString()) {

                case "Parral":
        //Para la localizacion de cada ciudad hay que ingresar su codigo WOEID para que Yahoo pueda encontrar
        //la ciudad que deseamos
                    int p = s.getForecast("124834", DegreeUnit.CELSIUS).getItem().getCondition().getTemp();
                    String temp = "";
                    temp = String.valueOf(p);
                    lblClima.setText(s.getForecast("124834", DegreeUnit.CELSIUS)
                            .getItem().getCondition().getText());
                    lblTemp.setText(temp+"°");
                    break;

                case "Chihuahua":
                    int c = s.getForecast("115958", DegreeUnit.CELSIUS).getItem().getCondition().getTemp();
                    String t = "";
                    t = String.valueOf(c);
                    lblClima.setText(s.getForecast("115958", DegreeUnit.CELSIUS)
                            .getItem().getCondition().getText());
                    lblTemp.setText(t+"°");
                    break;

                case "Ciudad Juarez":
                    int cj= s.getForecast("116556", DegreeUnit.CELSIUS).getItem().getCondition().getTemp();
                    String j = "";
                    j = String.valueOf(cj);
                    lblClima.setText(s.getForecast("116556", DegreeUnit.CELSIUS)
                            .getItem().getCondition().getText());
                    lblTemp.setText(j+"°");
                    break;

                case "Cuauhtemoc":
                    int ca = s.getForecast("145122", DegreeUnit.CELSIUS).getItem().getCondition().getTemp();
                    String tempe = "";
                    tempe = String.valueOf(ca);
                    lblClima.setText(s.getForecast("145122", DegreeUnit.CELSIUS)
                            .getItem().getCondition().getText());
                    lblTemp.setText(tempe+"°");
                    break;
                case "Delicias":
                    int d = s.getForecast("118131", DegreeUnit.CELSIUS).getItem().getCondition().getTemp();
                    String g = "";
                    g = String.valueOf(d);
                    lblClima.setText(s.getForecast("118131", DegreeUnit.CELSIUS)
                            .getItem().getCondition().getText());
                    lblTemp.setText(g+"°");
                    break;

            }
        } catch (JAXBException ex) {
            Logger.getLogger(frmClima.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmClima.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cboCiudadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmClima().setVisible(true);
                } catch (JAXBException ex) {
                    Logger.getLogger(frmClima.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(frmClima.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCiudades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClima;
    private javax.swing.JLabel lblTemp;
    // End of variables declaration//GEN-END:variables
}
